### PR TITLE
Fix delete wiki page function

### LINKED ISSUE #2621: Wiki cannot be deleted.
## Issue
**Impacted version**: 4.35.2

**Deployment mode**: *explain here how you use GitBucket : standalone app, with an http frontend (nginx, httpd, ...)*

**Problem description**:
- *WiKi cannot be deleted.*
- *An error occurs when NewFeed has a history of deleting WiKi.*

**Error log**:
```
gitbucket.core.helper.html.activities$.$anonfun$apply$1(activities.template.scala:47)
--
scala.collection.immutable.List.map(List.scala:246)
gitbucket.core.helper.html.activities$.apply(activities.template.scala:45)
gitbucket.core.html.index$.apply(index.template.scala:44)
gitbucket.core.controller.IndexControllerBase.$anonfun$$init$$2(IndexController.scala:67)
scala.Option.map(Option.scala:242)
gitbucket.core.controller.IndexControllerBase.$anonfun$$init$$1(IndexController.scala:65)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:282)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:276)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:180)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:171)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:35)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:275)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:274)
gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:250)
scala.Option.flatMap(Option.scala:283)
org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:248)
scala.collection.immutable.Stream.flatMap(Stream.scala:206)
org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:247)
org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:245)
gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2(CompositeScalatraFilter.scala:67)
gitbucket.core.servlet.CompositeScalatraFilter.$anonfun$process$2$adapted(CompositeScalatraFilter.scala:64)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
scala.collection.AbstractIterable.foreach(Iterable.scala:920)
gitbucket.core.servlet.CompositeScalatraFilter.process(CompositeScalatraFilter.scala:64)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:25)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
gitbucket.core.servlet.ControllerFilter.doFilter(CompositeScalatraFilter.scala:31)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:80)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:201)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:201)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:35)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:75)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:73)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:35)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:55)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:54)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:52)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:35)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:35)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:42)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:35)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:197)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:66)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:64)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:35)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:172)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:171)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:35)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:73)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.lang.Thread.run(Thread.java:748)
```

screenshot

### PR DESCRIPTION
**Pull request by onukura**
### Before submitting a pull-request to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] rebased my branch over master
- [x] verified that project is compiling
- [ ] verified that tests are passing
- [x] squashed my commits as appropriate *(keep several commits if it is relevant to understand the PR)*
- [x] [marked as closed using commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) all issue ID that this PR should correct

# About this PR

this PR fix #2621 

> WiKi cannot be deleted.

Caused by missing function call of wiki page deletion.

> An error occurs when NewFeed has a history of deleting WiKi.

Caused by missing support of "delete_wiki" event in template.

### CODE REVIEW

File: src/main/scala/gitbucket/core/controller/WikiController.scala [hunk 1]
```diff
@@ -250,17 +250,26 @@ trait WikiControllerBase extends ControllerBase {
...
+      defining(context.loginAccount.get) {
+        loginAccount =>
+          deleteWikiPage(
+            repository.owner,
+            repository.name,
+            pageName,
+            loginAccount.fullName,
+            loginAccount.mailAddress,
+            s"Destroyed ${pageName}"
+          )
```
Comment (takezoe) [inline src/main/scala/gitbucket/core/controller/WikiController.scala:262]: It didn't delete a wiki page! 😲

Comment (onukura) [reply src/main/scala/gitbucket/core/controller/WikiController.scala:262]: yeah...

**Comment by onukura** [comment]
@takezoe This bug is very troubling because the home page (dashboard) would be unavailable once user operate `delete wiki page` on GUI. So IMHO it would be better release 4.35.3. What do you think about this??

**Comment by takezoe** [comment]
@onukura That makes sense. I will release 4.35.3 later this week.
